############# 中文导航 ##############

# 主菜单
[[main]]
name = "首页"
url = "/"
weight = 1

[[main]]
name = "关于"
url = "/about"
weight = 2

[[main]]
name = "元素"
url = "/elements"
weight = 3

[[main]]
weight = 4
name = "页面"

[[main]]
parent = "页面"
name = "博客"
url = "/blog"

[[main]]
parent = "页面"
name = "联系我们"
url = "/contact"

[[main]]
parent = "页面"
name = "作者"
url = "/authors"

[[main]]
parent = "页面"
name = "分类"
url = "/categories"

[[main]]
parent = "页面"
name = "404 页面"
url = "/404"


# 页脚菜单
[[footer]]
name = "关于"
url = "/about"
weight = 1

[[footer]]
name = "元素"
url = "/elements"
weight = 2

[[footer]]
name = "隐私政策"
url = "/privacy-policy"
weight = 3
